### ISSUE TITLE
Memory cache sizing

### ISSUE THREAD

**Issue by moagrius** [kittinunf/Fuse#10]
Nice job on the library!

When looking at MemCache.kt, line 9https://github.com/kittinunf/Fuse/blob/master/fuse/src/main/kotlin/com/github/kittinunf/fuse/core/cache/MemCache.kt#L9, I can see that you're setting the size of the cache to 1/8th of the avialable memory, as is described here: https://developer.android.com/topic/performance/graphics/cache-bitmap.html#memory-cache

However, you're not overriding `sizeOf`, so I believe you'll accept a number of _items_ equal to that value, rather than the number of _kilobytes_.

Or did I miss something?

**Comment by kittinunf** [comment]
Wow! you are right! I think my original implementation is not correct. I will find time to correct it, if you feel fancy you can open a PR for them too.

**Comment by moagrius** [comment]
PR'ed https://github.com/kittinunf/Fuse/pull/11

**Comment by kittinunf** [comment]
New version of Fuse allows users to supply their own implementation of `LruCache`

For example,
```kotlin
defaultAndroidMemoryCache(object : LruCache<String, Any> () {

})
```

So, I don't think this is an issue anymore! I know that this is long overdue but please try new version 🙏
