### ISSUE TITLE
Exposing Put

### ISSUE THREAD

**Issue by mradzinski** [kittinunf/Fuse#13]
Is there a reason why `put` isn't exposed like in any regular caching library? 

There're certain use cases where you want to update the cache without getting its content, plus it isn't very convenient when used in conjunction with RxJava given its async nature.

**Comment by kittinunf** [comment]
Actually, no. It is just a overlook on my side! I will comeback and working on this.

**Comment by kittinunf** [comment]
It is probably long overdue, but I just released the new version! `1.0.0-alpha1`

I think I have fixed your concerns already. If you have moved on to something else, no worries! But if you have a need to try Fuse again, please do so! Thanks
