### ISSUE TITLE
integration with Fuel

### ISSUE THREAD

**Issue by UmarBhutta** [kittinunf/Fuse#7]
How can i use this with Fuel. as i want local cache inside my app which have a lot of network calls?

**Comment by kittinunf** [comment]
You can either integrate this via `ResponseInterceptor` e.g. 

``` Kotlin
inline fun <reified T> FuseCacheResponseInterceptor() =
        { next: (Request, Response) -> Response ->
            { req: Request, res: Response ->
                val cacheKey = .... 
                Fuse.stringCache.set(cacheKey, res.data)
                next(req, res)
            }
        }
```

If you want to the next network call to be skipped, you have to add a custom `Client` to tell `Fuel` not to call network after it was being cached or depending on your use cases.




Another way is to use `via` Fuse itself by proving a Fuel flavor `fetcher` class like

``` Kotlin
class FuelFetcher<T> : Fetcher<T>, Fuse.DataConvertible<T> by convertible {
    override val key: String = url.toString()

    private var cancelled: Boolean = false
   
    private val manager: FuelManager

   init {
       manager = FuelManager()
   }
 
    override fun fetch(handler: (Result<T, Exception>) -> Unit) {
       Fuel.get("http://httpbin.org/get").response<T>(handler)
    }
   
   override fun cancel() {
      //if you want to cancel, you need to hold on to the Request object
   }
}
```

Then use like

``` Kotlin
Fuse.jsonCache.get(fetcher = FuelFetcher()) { result ->
  //do something with result ...
}
```

I hope that answer your question. Please do not hesitate to ask if you find it not clear enough.

**Comment by UmarBhutta** [comment]
`Fuse.stringCache.set(cacheKey, res.data) `

that is the line which was bothering me from the start as per library set method is private. how can i access that ?

**Comment by kittinunf** [comment]
Ohhh you are right!!! Sorry for not understanding your question from the beginning. Let me work on the fix for this.

**Comment by coolirisroto** [comment]
the error was fixed?

**Comment by shkschneider** [comment]
Yeah, `set()`/`put()` is Private oO

**Comment by kittinunf** [comment]
It is no longer is! I think I have fixed your concern already in the newest version!
